# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mot_toolbox_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(567, 511)
        self.set_box = QtWidgets.QComboBox(Dialog)
        self.set_box.setGeometry(QtCore.QRect(90, 50, 121, 22))
        self.set_box.setObjectName("set_box")
        self.set_box.addItem("Train")
        self.set_box.addItem("Test")
        self.set_box.addItem("All")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 60, 54, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 190, 481, 271))
        self.label_2.setObjectName("label_2")
        self.mot_path = QtWidgets.QLineEdit(Dialog)
        self.mot_path.setGeometry(QtCore.QRect(90, 11, 241, 20))
        self.mot_path.setObjectName("mot_path")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 11, 51, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 100, 54, 12))
        self.label_4.setObjectName("label_4")
        self.seq_box = QtWidgets.QComboBox(Dialog)
        self.seq_box.setGeometry(QtCore.QRect(90, 90, 241, 22))
        self.seq_box.setObjectName("seq_box")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 140, 471, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.playButton = QtWidgets.QPushButton(self.layoutWidget)
        self.playButton.setObjectName("playButton")
        self.horizontalLayout.addWidget(self.playButton)
        self.gtButton = QtWidgets.QPushButton(self.layoutWidget)
        self.gtButton.setObjectName("gtButton")
        self.horizontalLayout.addWidget(self.gtButton)
        self.detButton = QtWidgets.QPushButton(self.layoutWidget)
        self.detButton.setObjectName("detButton")
        self.horizontalLayout.addWidget(self.detButton)
        self.stopButton = QtWidgets.QPushButton(self.layoutWidget)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout.addWidget(self.stopButton)
        self.seqFreshButton = QtWidgets.QPushButton(Dialog)
        self.seqFreshButton.setGeometry(QtCore.QRect(340, 10, 71, 23))
        self.seqFreshButton.setObjectName("seqFreshButton")

        self.retranslateUi(Dialog)
        self.playButton.clicked.connect(Dialog.displayBT)
        self.gtButton.clicked.connect(Dialog.gtBT)
        self.detButton.clicked.connect(Dialog.detBT)
        self.stopButton.clicked.connect(Dialog.stopBT)
        self.seqFreshButton.clicked.connect(Dialog.fresh_seq)
        self.set_box.currentIndexChanged['QString'].connect(Dialog.fresh_seq)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Dataset"))
        self.label_2.setText(_translate("Dialog", "TextLabel"))
        self.label_3.setText(_translate("Dialog", "Path"))
        self.label_4.setText(_translate("Dialog", "Sequence"))
        self.playButton.setText(_translate("Dialog", "Display Video"))
        self.gtButton.setText(_translate("Dialog", "Ground Truth"))
        self.detButton.setText(_translate("Dialog", "Detection"))
        self.stopButton.setText(_translate("Dialog", "Stop"))
        self.seqFreshButton.setText(_translate("Dialog", "Refresh"))
